# Generated by Django 3.2.9 on 2021-12-03 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211203_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 6, 7, 35, 592629)),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 6, 7, 35, 591840)),
        ),
    ]
