# Generated by Django 3.2.9 on 2021-12-01 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=155)),
                ('number', models.CharField(max_length=13)),
                ('sum', models.IntegerField()),
                ('type_person', models.CharField(choices=[('jismoniy_shaxs', 'jismoniy shaxs'), ('yuridik_shaxs', 'yuridik shaxs')], max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 1, 6, 40, 10, 507143))),
                ('status', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('moderation', 'moderation'), ('new', 'new')], default='new', max_length=31)),
            ],
        ),
    ]
