# Generated by Django 3.2.9 on 2021-12-01 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 7, 13, 16, 598762)),
        ),
    ]
