# Generated by Django 3.2.9 on 2021-12-02 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_applicationmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 9, 27, 40, 602694)),
        ),
    ]
