# Generated by Django 3.2.9 on 2021-12-03 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_applicationmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 6, 0, 43, 479675)),
        ),
    ]
